### ISSUE TITLE
Crash when using sentry-log4j: java.lang.NoSuchMethodError: io.sentry.SentryClient.getMdcTags()Ljava/util/Set;

### ISSUE THREAD

**Issue by not-raspberry** [getsentry/sentry-clj#12]
This is probably reproducible in Java.

Minimal reproduction: https://github.com/not-raspberry/sentry-clojure-log4j-repro

Dependencies: https://github.com/not-raspberry/sentry-clojure-log4j-repro/blob/master/project.clj#L7-L11

Output:
```
$ lein run
2017-11-17 14:21:20,477 ERROR sentry-repro.core: ERROR
2017-11-17 14:21:20,492 INFO  io.sentry.DefaultSentryClientFactory: Using an HTTPS connection to Sentry.
Exception in thread "main" java.lang.NoSuchMethodError: io.sentry.SentryClient.getMdcTags()Ljava/util/Set;, compiling:(/tmp/form-init720909482945021916.clj:1:72)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NoSuchMethodError: io.sentry.SentryClient.getMdcTags()Ljava/util/Set;
        at io.sentry.log4j.SentryAppender.createEventBuilder(SentryAppender.java:131)
        at io.sentry.log4j.SentryAppender.append(SentryAppender.java:84)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:498)
        at clojure.tools.logging$eval436$fn__441.invoke(logging.clj:286)
        at clojure.tools.logging.impl$eval178$fn__192$G__169__203.invoke(impl.clj:16)
        at clojure.tools.logging$log_STAR_.invokeStatic(logging.clj:64)
        at clojure.tools.logging$log_STAR_.invoke(logging.clj:43)
        at sentry_repro.core$_main.invokeStatic(core.clj:7)
        at sentry_repro.core$_main.doInvoke(core.clj:6)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at user$eval3130.invokeStatic(form-init720909482945021916.clj:1)
        at user$eval3130.invoke(form-init720909482945021916.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 14 more
2017-11-17 14:21:20,501 INFO  io.sentry.connection.AsyncConnection: Automatic shutdown of the async connection
2017-11-17 14:21:20,501 INFO  io.sentry.connection.AsyncConnection: Gracefully shutdown sentry threads.
2017-11-17 14:21:20,501 INFO  io.sentry.connection.AsyncConnection: Shutdown finished.
```

**Comment by bretthoerner** [comment]
Thanks for the report. The issue here is that `sentry-clj` is pulling in a dated version of `sentry`. It can be fixed in two ways:

1. Include `sentry-log4j` before `sentry-clj` so that the newer `sentry` "wins".
2. Manually include the newer sentry:

```diff
diff --git a/project.clj b/project.clj
index eeeede0..4f09d61 100644
--- a/project.clj
+++ b/project.clj
@@ -8,6 +8,7 @@
                  [org.clojure/tools.logging "0.4.0"]
                  [org.slf4j/slf4j-log4j12 "1.7.25"]
                  [io.sentry/sentry-clj "0.5.1"]
+                 [io.sentry/sentry "1.6.3"]
                  [io.sentry/sentry-log4j "1.6.3"]
                  ]
   :main ^:skip-aot sentry-repro.core
```

All that said, I'll make a new `sentry-clj` release that has a more recent `sentry` dep. Thanks for the report!
