### ISSUE TITLE
Event not sent to Sentry if data in ExceptionInfo exception is not GSON serializable

### ISSUE THREAD

**Issue by johncowie** [getsentry/sentry-clj#31]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`[io.sentry/sentry-clj "5.0.152"]`

### Steps to Reproduce

Run the following clojure code in a REPL:

```clojure
(do
    (require '[clj-http.client :as http])             ;; requires [clj-http/clj-http "3.10.3"]
    (require '[sentry-clj.core :as sentry])

    (sentry/init! **DSN** ;; replace with DSN from Sentry account
                  {:debug true})
    (try
      (http/get "http://example.com/non-existent")
      (catch Exception e
        (sentry/send-event {:message (.getMessage e) :throwable e}))))
```

### Expected Result

I hoped that the exception would be successfully sent to Sentry.

### Actual Result

Logging output (Debug mode is turned on):
```
INFO: Initializing SDK with DSN: ******
INFO: No outbox dir path is defined in options.
INFO: GlobalHubMode: 'false'
DEBUG: UncaughtExceptionHandlerIntegration enabled: true
DEBUG: UncaughtExceptionHandlerIntegration installed.
DEBUG: ShutdownHookIntegration installed.
DEBUG: Capturing event: fdd3e89775334596ba7f56dc8ed159d1
INFO: Session is null on scope.withSession
=> "fdd3e89775334596ba7f56dc8ed159d1"
ERROR: Failed to create envelope item. Dropping it.
java.lang.IllegalArgumentException: class org.apache.http.impl.client.InternalHttpClient declares multiple JSON fields named log
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.toJson(Gson.java:696)
	at com.google.gson.Gson.toJsonTree(Gson.java:597)
	at com.google.gson.Gson.toJsonTree(Gson.java:576)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at io.sentry.adapters.MapAdapter.serialize(MapAdapter.java:28)
	at io.sentry.adapters.MapAdapter.serialize(MapAdapter.java:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.write(UnknownPropertiesTypeAdapterFactory.java:103)
	at io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.write(UnknownPropertiesTypeAdapterFactory.java:58)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at io.sentry.GsonSerializer.serialize(GsonSerializer.java:143)
	at io.sentry.SentryEnvelopeItem.lambda$fromEvent$3(SentryEnvelopeItem.java:109)
	at io.sentry.SentryEnvelopeItem$CachedItem.getBytes(SentryEnvelopeItem.java:256)
	at io.sentry.SentryEnvelopeItem.lambda$fromEvent$5(SentryEnvelopeItem.java:122)
	at io.sentry.SentryEnvelopeItem.getData(SentryEnvelopeItem.java:56)
	at io.sentry.GsonSerializer.serialize(GsonSerializer.java:173)
	at io.sentry.transport.HttpConnection.send(HttpConnection.java:155)
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:210)
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

ERROR: Request failed, API returned 400
ERROR: {"detail":"empty envelope"}
ERROR: The transport failed to send the envelope with response code 400
ERROR: Envelope submission failed 
 java.lang.IllegalStateException: The transport failed to send the envelope with response code 400
java.lang.IllegalStateException: The transport failed to send the envelope with response code 400
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:220)
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Additional Info
It seems that the problem is that the `clj-http` library includes the client object in the map of `ex-info` data when constructing an `ex-info` exception for an unsuccessful HTTP response.  `sentry-clj` indiscriminately merges all of the data returned from `ex-data` into the context of the Sentry event, which causes the underlying Java library to fail if values in the data aren't serializable as JSON.

**Comment by eigenhombre** [comment]
We also have this exact same issue.

**Comment by dharrigan** [comment]
Hi,

It looks like the Sentry Java library is undergoing some changes with regards to JSON Serialisation (see linked issue). Perhaps it would be prudent to wait until that beds in before any changes are made in this library?

**Comment by marandaneto** [comment]
should be solved by the 6.0.0 release, See Draft PR https://github.com/getsentry/sentry-java/pull/1791/files (JsonObjectSerializer and JsonReflectionObjectSerializer), if we don't know how to serialize a property, we call `.toString()` and do not fail event sending.

**Comment by gtrak** [comment]
It's been a while, we hit this issue and did some digging. Probably the right thing to do here is to track the alpha version of the java lib with a corresponding clojure branch?

Another alternative might be to have a fallback if an exception is not serialized successfully with some stringifying.

Stringifying all vals all the time might be too aggressive.

**Comment by dharrigan** [comment]
Hi!

So, I've done a bit of work in this area, upgrading the library to Sentry 6.3.X. I have, however, hit upon a problem with a sorta-klunky workaround.

It appears, that doing this

` (sentry/send-event {:message (.getMessage e) :throwable e}))))`

Causes a near infinite circular reference when serializing out the exception (throwable), issued from this location:

https://github.com/getsentry/sentry-java/blob/f75a0a72562aca92dd90305ffd1f95e6ed6e93fb/sentry/src/main/java/io/sentry/JsonReflectionObjectSerializer.java#L44

If, however, I set the maxDepth to (a finger-in-the-air) value of 2, then it works and meaningful information is sent to sentry.

So the question is, is that good enough? Added in a `max-depth` into the `sentry-options` configuration when initialising sentry. Set it to a low value (if necessary, by default it is set to max depth of 100) if you experience a circule reference loop.
